dist: xenial
language: python
python:
- "3.6"

# setup environment
install:
- pip install -r requirements.txt

# run test scripts
script:
- cd Shop-them-all
- python manage.py migrate
- python manage.py collectstatic
- python manage.py test