# Generated by Django 2.2.1 on 2019-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190527_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iulia',
        ),
        migrations.DeleteModel(
            name='Smth',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
