# Generated by Django 2.2.1 on 2019-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190528_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AddField(
            model_name='shop',
            name='xMap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='yMap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
